# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld/stock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16helloworld/stock.proto\x12\nhelloworld\x1a\x1cgoogle/api/annotations.proto\"\x1c\n\x0cStockRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nStockReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb5\x01\n\x05Stock\x12k\n\x08SayHello\x12\x18.helloworld.StockRequest\x1a\x16.helloworld.StockReply\"-\x82\xd3\xe4\x93\x02\'\x12\r/stock/{name}Z\x16\"\x11/stock/stock_info:\x01*\x12?\n\x07\x43hannle\x12\x18.helloworld.StockRequest\x1a\x16.helloworld.StockReply(\x01\x30\x01\x42g\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01Z5google.golang.org/grpc/examples/helloworld/helloworldb\x06proto3')



_STOCKREQUEST = DESCRIPTOR.message_types_by_name['StockRequest']
_STOCKREPLY = DESCRIPTOR.message_types_by_name['StockReply']
StockRequest = _reflection.GeneratedProtocolMessageType('StockRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOCKREQUEST,
  '__module__' : 'helloworld.stock_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.StockRequest)
  })
_sym_db.RegisterMessage(StockRequest)

StockReply = _reflection.GeneratedProtocolMessageType('StockReply', (_message.Message,), {
  'DESCRIPTOR' : _STOCKREPLY,
  '__module__' : 'helloworld.stock_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.StockReply)
  })
_sym_db.RegisterMessage(StockReply)

_STOCK = DESCRIPTOR.services_by_name['Stock']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001Z5google.golang.org/grpc/examples/helloworld/helloworld'
  _STOCK.methods_by_name['SayHello']._options = None
  _STOCK.methods_by_name['SayHello']._serialized_options = b'\202\323\344\223\002\'\022\r/stock/{name}Z\026\"\021/stock/stock_info:\001*'
  _STOCKREQUEST._serialized_start=68
  _STOCKREQUEST._serialized_end=96
  _STOCKREPLY._serialized_start=98
  _STOCKREPLY._serialized_end=127
  _STOCK._serialized_start=130
  _STOCK._serialized_end=311
# @@protoc_insertion_point(module_scope)
