# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from helloworld import helloword_pb2 as helloworld_dot_helloword__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/hellostreamingworld.Greeter/SayHello',
                request_serializer=helloworld_dot_helloword__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloworld_dot_helloword__pb2.HelloReply.FromString,
                )
        self.SayHelloReplyStream = channel.unary_stream(
                '/hellostreamingworld.Greeter/SayHelloReplyStream',
                request_serializer=helloworld_dot_helloword__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloworld_dot_helloword__pb2.HelloReply.FromString,
                )
        self.SayHelloRequestStream = channel.stream_unary(
                '/hellostreamingworld.Greeter/SayHelloRequestStream',
                request_serializer=helloworld_dot_helloword__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloworld_dot_helloword__pb2.HelloReply.FromString,
                )
        self.SayHelloStream = channel.stream_stream(
                '/hellostreamingworld.Greeter/SayHelloStream',
                request_serializer=helloworld_dot_helloword__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloworld_dot_helloword__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends multiple greetings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloReplyStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloRequestStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=helloworld_dot_helloword__pb2.HelloRequest.FromString,
                    response_serializer=helloworld_dot_helloword__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloReplyStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHelloReplyStream,
                    request_deserializer=helloworld_dot_helloword__pb2.HelloRequest.FromString,
                    response_serializer=helloworld_dot_helloword__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloRequestStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SayHelloRequestStream,
                    request_deserializer=helloworld_dot_helloword__pb2.HelloRequest.FromString,
                    response_serializer=helloworld_dot_helloword__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SayHelloStream,
                    request_deserializer=helloworld_dot_helloword__pb2.HelloRequest.FromString,
                    response_serializer=helloworld_dot_helloword__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hellostreamingworld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hellostreamingworld.Greeter/SayHello',
            helloworld_dot_helloword__pb2.HelloRequest.SerializeToString,
            helloworld_dot_helloword__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloReplyStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/hellostreamingworld.Greeter/SayHelloReplyStream',
            helloworld_dot_helloword__pb2.HelloRequest.SerializeToString,
            helloworld_dot_helloword__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloRequestStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/hellostreamingworld.Greeter/SayHelloRequestStream',
            helloworld_dot_helloword__pb2.HelloRequest.SerializeToString,
            helloworld_dot_helloword__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/hellostreamingworld.Greeter/SayHelloStream',
            helloworld_dot_helloword__pb2.HelloRequest.SerializeToString,
            helloworld_dot_helloword__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
