# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from helloworld import stock_pb2 as helloworld_dot_stock__pb2


class StockStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/helloworld.Stock/SayHello',
                request_serializer=helloworld_dot_stock__pb2.StockRequest.SerializeToString,
                response_deserializer=helloworld_dot_stock__pb2.StockReply.FromString,
                )
        self.Channle = channel.stream_stream(
                '/helloworld.Stock/Channle',
                request_serializer=helloworld_dot_stock__pb2.StockRequest.SerializeToString,
                response_deserializer=helloworld_dot_stock__pb2.StockReply.FromString,
                )


class StockServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Channle(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=helloworld_dot_stock__pb2.StockRequest.FromString,
                    response_serializer=helloworld_dot_stock__pb2.StockReply.SerializeToString,
            ),
            'Channle': grpc.stream_stream_rpc_method_handler(
                    servicer.Channle,
                    request_deserializer=helloworld_dot_stock__pb2.StockRequest.FromString,
                    response_serializer=helloworld_dot_stock__pb2.StockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Stock', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Stock(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Stock/SayHello',
            helloworld_dot_stock__pb2.StockRequest.SerializeToString,
            helloworld_dot_stock__pb2.StockReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Channle(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/helloworld.Stock/Channle',
            helloworld_dot_stock__pb2.StockRequest.SerializeToString,
            helloworld_dot_stock__pb2.StockReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
