// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: helloworld/stock.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StockClient is the client API for Stock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockReply, error)
	Channle(ctx context.Context, opts ...grpc.CallOption) (Stock_ChannleClient, error)
}

type stockClient struct {
	cc grpc.ClientConnInterface
}

func NewStockClient(cc grpc.ClientConnInterface) StockClient {
	return &stockClient{cc}
}

func (c *stockClient) SayHello(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockReply, error) {
	out := new(StockReply)
	err := c.cc.Invoke(ctx, "/helloworld.Stock/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockClient) Channle(ctx context.Context, opts ...grpc.CallOption) (Stock_ChannleClient, error) {
	stream, err := c.cc.NewStream(ctx, &Stock_ServiceDesc.Streams[0], "/helloworld.Stock/Channle", opts...)
	if err != nil {
		return nil, err
	}
	x := &stockChannleClient{stream}
	return x, nil
}

type Stock_ChannleClient interface {
	Send(*StockRequest) error
	Recv() (*StockReply, error)
	grpc.ClientStream
}

type stockChannleClient struct {
	grpc.ClientStream
}

func (x *stockChannleClient) Send(m *StockRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stockChannleClient) Recv() (*StockReply, error) {
	m := new(StockReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StockServer is the server API for Stock service.
// All implementations must embed UnimplementedStockServer
// for forward compatibility
type StockServer interface {
	// Sends a greeting
	SayHello(context.Context, *StockRequest) (*StockReply, error)
	Channle(Stock_ChannleServer) error
	mustEmbedUnimplementedStockServer()
}

// UnimplementedStockServer must be embedded to have forward compatible implementations.
type UnimplementedStockServer struct {
}

func (UnimplementedStockServer) SayHello(context.Context, *StockRequest) (*StockReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedStockServer) Channle(Stock_ChannleServer) error {
	return status.Errorf(codes.Unimplemented, "method Channle not implemented")
}
func (UnimplementedStockServer) mustEmbedUnimplementedStockServer() {}

// UnsafeStockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServer will
// result in compilation errors.
type UnsafeStockServer interface {
	mustEmbedUnimplementedStockServer()
}

func RegisterStockServer(s grpc.ServiceRegistrar, srv StockServer) {
	s.RegisterService(&Stock_ServiceDesc, srv)
}

func _Stock_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Stock/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).SayHello(ctx, req.(*StockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stock_Channle_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StockServer).Channle(&stockChannleServer{stream})
}

type Stock_ChannleServer interface {
	Send(*StockReply) error
	Recv() (*StockRequest, error)
	grpc.ServerStream
}

type stockChannleServer struct {
	grpc.ServerStream
}

func (x *stockChannleServer) Send(m *StockReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stockChannleServer) Recv() (*StockRequest, error) {
	m := new(StockRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Stock_ServiceDesc is the grpc.ServiceDesc for Stock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Stock",
	HandlerType: (*StockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Stock_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channle",
			Handler:       _Stock_Channle_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld/stock.proto",
}
